service: backend
app: spotlightme
org: abhi5415

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  app:
    handler: index.handler
    events:
      - http: GET /
    environment:
      AIRTABLE_KEY: ${param:AIRTABLE_KEY}
