service: backend
app: spotlightme
org: abhi5415

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  app:
    handler: index.handler
    events:
      - http: GET /
    environment:
      AIRTABLE_KEY: ${param:AIRTABLE_KEY}
      ACCESS_KEY: ${param:ACCESS_KEY}
      SECRET_KEY: ${param:SECRET_KEY}
      BUCKET: ${param:BUCKET}

    # iamRoleStatements:
    #   - Effect: Allow
    #   Action:
    #     - s3:PutObject
    #     - s3:DeleteObject
    #     - s3:ListBucket
    #     - s3:GetObject
    #   Resource: arn:aws:s3::spotlightme
